### ISSUE TITLE
Error at end the execution

### ISSUE THREAD

**Issue by angel-ayala** [kengz/SLM-Lab#142]
Hi, 
I get stuck at the end of the trial, when it finish, can't create the respective graphics, i got the next traceback error, what can it be?

Traceback (most recent call last):
  File "run_lab.py", line 63, in <module>
    main()
  File "run_lab.py", line 59, in main
    run_by_mode(spec_file, spec_name, lab_mode)
  File "run_lab.py", line 38, in run_by_mode
    Trial(spec).run()
  File "/home/kelo/librerias/SLM-Lab/slm_lab/experiment/control.py", line 122, in run
    session_datas = util.parallelize_fn(self.init_session_and_run, info_spaces, num_cpus)
  File "/home/kelo/librerias/SLM-Lab/slm_lab/lib/util.py", line 533, in parallelize_fn
    results = pool.map(fn, args)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
ValueError: Invalid property specified for object of type plotly.graph_objs.Layout: 'yaxis2'

**Comment by angel-ayala** [comment]
Oh i forgot to mention, i'm running the demo spec just testing the installation.

**Comment by kengz** [comment]
Hmm never seen that before. Could you include some info?
- the last few lines of the info logged to the terminal, for example the reward, loss etc. 
- what is your OS?
- what is the output if you run this in the terminal:  `yarn global list --pattern=orca`

**Comment by kengz** [comment]
hmm thread probably at up some of the backtrace. Seems like you're hitting the parallelization logic.
Could u run in dev mode: change `config/experiment.json` to use `"demo.json": "dev"`. Then it should not use threading, and perhaps the log will be more verbose

**Comment by angel-ayala** [comment]
here it goes:

[2018-07-18 01:36:55,287 INFO monitor.py:l219] dqn_cartpole trial 0 session 0 env 0, body (0, 0, 0), epi 150, t 161, loss: 3.1090, total_reward: 161.00, last-100-epi avg: 177.40
[2018-07-18 01:36:55,562 INFO analysis.py:l299] Analyzing session
[2018-07-18 01:36:56,423 INFO analysis.py:l83] Session mean fitness: 2.2808407146360046
   strength     speed  stability
0  0.954514  3.753754   0.777778
This is the format of your plot grid:
[ (1,1) x1,y1 ]
[ (2,1) x1,y2 ]
[ (3,1) x1,y3 ]

/usr/lib/python3.6/site-packages/plotly/graph_objs/_deprecations.py:396: DeprecationWarning:

plotly.graph_objs.Margin is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.layout.Margin


Traceback (most recent call last):
  File "run_lab.py", line 63, in <module>
    main()
  File "run_lab.py", line 59, in main
    run_by_mode(spec_file, spec_name, lab_mode)
  File "run_lab.py", line 50, in run_by_mode
    Trial(spec).run()
  File "/home/kelo/librerias/SLM-Lab/slm_lab/experiment/control.py", line 126, in run
    session_data = self.init_session_and_run(info_space)
  File "/home/kelo/librerias/SLM-Lab/slm_lab/experiment/control.py", line 109, in init_session_and_run
    session_data = session.run()
  File "/home/kelo/librerias/SLM-Lab/slm_lab/experiment/control.py", line 82, in run
    self.data = analysis.analyze_session(self)  # session fitness
  File "/home/kelo/librerias/SLM-Lab/slm_lab/experiment/analysis.py", line 305, in analyze_session
    session_fig = plot_session(session.spec, session.info_space, session_data)
  File "/home/kelo/librerias/SLM-Lab/slm_lab/experiment/analysis.py", line 142, in plot_session
    fig_2 = viz.plot_line(aeb_df, ['loss'], 'epi', y2_col=['explore_var'], trace_kwargs={'legendgroup': aeb_str, 'showlegend': False, 'line': {'color': palette[idx]}}, draw=False)
  File "/home/kelo/librerias/SLM-Lab/slm_lab/lib/viz.py", line 207, in plot_line
    **kwargs)
  File "/home/kelo/librerias/SLM-Lab/slm_lab/lib/viz.py", line 136, in plot_go
    side='right', overlaying='y1', anchor='x1',
  File "/usr/lib/python3.6/site-packages/plotly/basedatatypes.py", line 2829, in update
    BaseFigure._perform_update(self, dict1)
  File "/usr/lib/python3.6/site-packages/plotly/basedatatypes.py", line 2109, in _perform_update
    plotly_obj._raise_on_invalid_property_error(*invalid_props)
  File "/usr/lib/python3.6/site-packages/plotly/basedatatypes.py", line 2802, in _raise_on_invalid_property_error
    prop_descriptions=self._prop_descriptions))
ValueError: Invalid property specified for object of type plotly.graph_objs.Layout: 'yaxis2'

**Comment by kengz** [comment]
Seems to be some issue caused by Plotly's internal methods. If you do `conda activate lab; conda list` does it show Plotly is at version 2.2.3?

**Comment by angel-ayala** [comment]
i have incorrectly installed the plotly v3, however i correct it, run `conda list` and now appear the line `plotly                    2.2.3                    py36_0    conda-forge` but when i run `yarn start` gives me the ModuleNotFoundError 

`yarn run v1.7.0
$ python3 run_lab.py
Traceback (most recent call last):
  File "run_lab.py", line 9, in <module>
    from slm_lab.experiment.control import Session, Trial, Experiment
  File "/home/kelo/librerias/SLM-Lab/slm_lab/experiment/control.py", line 9, in <module>
    from slm_lab.experiment import analysis, search
  File "/home/kelo/librerias/SLM-Lab/slm_lab/experiment/analysis.py", line 7, in <module>
    from slm_lab.lib import logger, util, viz
  File "/home/kelo/librerias/SLM-Lab/slm_lab/lib/viz.py", line 5, in <module>
    from plotly import (
ModuleNotFoundError: No module named 'plotly'
error Command failed with exit code 1.
`

**Comment by kengz** [comment]
Some Linux distri seems to not let use inherit the shell variables. Try using plain command `python run_lab.py` instead of yarn (with conda activated  of course)

**Comment by angel-ayala** [comment]
oh great, it worked!
thanks a lot for your time.

**Comment by kengz** [comment]
Thank you too! This is useful information, now I know there'll be breakage with newer version of Plotly; good to watch out for.
