### ISSUE TITLE
Something funny in `util.parallelize_fn`

### ISSUE THREAD

**Issue by mwcvitkovic** [kengz/SLM-Lab#173]
After a fresh install on MacOS, running the demo works fine in "dev" mode, but in "train" mode there's an immediate crash with:
```
Traceback (most recent call last):
  File "run_lab.py", line 75, in <module>
    main()
  File "run_lab.py", line 70, in main
    run_by_mode(spec_file, spec_name, lab_mode)
  File "run_lab.py", line 48, in run_by_mode
    Trial(spec, info_space).run()
  File "/Users/mwcvitkovic/Projects/kengz-SLM-Lab/slm_lab/experiment/control.py", line 240, in run
    session_datas = self.run_sessions()
  File "/Users/mwcvitkovic/Projects/kengz-SLM-Lab/slm_lab/experiment/control.py", line 190, in run_sessions
    session_datas = util.parallelize_fn(self.init_session_and_run, info_spaces, ps.get(self.spec['meta'], 'resources.num_cpus', util.NUM_CPUS))
  File "/Users/mwcvitkovic/Projects/kengz-SLM-Lab/slm_lab/lib/util.py", line 397, in parallelize_fn
    pool = mp.Pool(num_cpus, initializer=pool_init, maxtasksperchild=1)
  File "/Users/mwcvitkovic/miniconda3/envs/lab/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/Users/mwcvitkovic/miniconda3/envs/lab/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/Users/mwcvitkovic/miniconda3/envs/lab/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/Users/mwcvitkovic/miniconda3/envs/lab/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/Users/mwcvitkovic/miniconda3/envs/lab/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/mwcvitkovic/miniconda3/envs/lab/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/mwcvitkovic/miniconda3/envs/lab/lib/python3.6/multiprocessing/popen_fork.py", line 26, in __init__
    self._launch(process_obj)
  File "/Users/mwcvitkovic/miniconda3/envs/lab/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/mwcvitkovic/miniconda3/envs/lab/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'parallelize_fn.<locals>.pool_init'
```

**Comment by kengz** [comment]
seems like I broke something when doing #170 . will look
