### ISSUE TITLE
missing module cv2

### ISSUE THREAD

**Issue by LodeVanB** [kengz/SLM-Lab#297]
/SLM-Lab/slm_lab/lib/util.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**To Reproduce**
1. OS used: Ubuntu 18 LTS
2. SLM-Lab git: git cloned
3.  demo.json not working

**Additional context**
had to add cmake libgcc manually

**Error logs**
(base) l*@l*-HP-Pavilion-dv7-PC:~/SLM-Lab$ python3 run_lab.py slm_lab/spec/demo.json dqn_cartpole dev
Traceback (most recent call last):
  File "run_lab.py", line 10, in <module>
    from slm_lab.experiment import analysis, retro_analysis
  File "/home/l*/SLM-Lab/slm_lab/experiment/analysis.py", line 5, in <module>
    from slm_lab.agent import AGENT_DATA_NAMES
  File "/home/l*r/SLM-Lab/slm_lab/agent/__init__.py", line 21, in <module>
    from slm_lab.agent import algorithm, memory
  File "/home/l*/SLM-Lab/slm_lab/agent/algorithm/__init__.py", line 8, in <module>
    from .actor_critic import *
  File "/home/l*/SLM-Lab/slm_lab/agent/algorithm/actor_critic.py", line 1, in <module>
    from slm_lab.agent import net
  File "/home/l*/SLM-Lab/slm_lab/agent/net/__init__.py", line 6, in <module>
    from slm_lab.agent.net.conv import *
  File "/home/l*/SLM-Lab/slm_lab/agent/net/conv.py", line 1, in <module>
    from slm_lab.agent.net import net_util
  File "/home/l*/SLM-Lab/slm_lab/agent/net/net_util.py", line 3, in <module>
    from slm_lab.lib import logger, util
  File "/home/l*r/SLM-Lab/slm_lab/lib/logger.py", line 1, in <module>
    from slm_lab.lib import util
  File "/home/l*/SLM-Lab/slm_lab/lib/util.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
```

**Comment by kengz** [comment]
Hi @LodeVanB seems like you did not activate the conda environment. Try running `conda activate lab` before running a lab command

**Comment by LodeVanB** [comment]
kengz,
 It doesn't work in (lab) either ... there is no module cv2 and for my ubuntu distro it isn't apparently not available if I try to install it with pip ...

**Comment by kengz** [comment]
oh multiarray error. Did u do the extra unity installation? If so, uninstall tensorflow and retry. just activate the environment and run `pip uninstall tensorflow`

**Comment by LodeVanB** [comment]
I use tensorflow in other projects, why should I uninstall it?

**Comment by kengz** [comment]
that's the purpose of using a conda virtual environment, so each project has its own environment. tensorflow causes the multiarray error u saw.

**Comment by kengz** [comment]
closing as resolved.
